[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? '\<C-n>' :
    \ neosnippet#expandable_or_jumpable() ?
    \ '\<Plug>(neosnippet_expand_or_jump)' : '\<tab>'
'''


[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_ft = ['snippet']
on_event = 'InsertEnter'
hook_add = '''
  " plugin key-mappings.
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  " superTab like snippets behavior.
  "imap <expr><TAB>
  "  \ pumvisible() ? "\<C-n>" :
  "  \ neosnippet#expandable_or_jumpable() ?
  "  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  " for conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''


[[plugins]]
repo = 'Shougo/neosnippet-snippets'
